apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: portal-api
  namespace: instance-3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: portal-api
  template:
    metadata:
      labels:
        app: portal-api
    spec:
      containers:
        - image: abiosoft/caddy
          name: portal-api
          ports:
            - containerPort: 2015
